routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => ['auth']],function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('product','ProductController');
    Route::resource('customer','CustomerController');
    Route::resource('so','SOController');
    Route::get('getCustomer','SOController@getCustomer')->name('getCustomer');
    Route::get('getProduct','SOController@getProduct')->name('getProduct');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
    protected $fillable = [
        'product_name',
        'item_type',
        'price',
        'diskon_price',
    ];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        $product_name = $request->product_name;
        $products = Product::where('product_name','LIKE','%'.$product_name.'%')
        ->paginate(50);
        return view('product.index',compact('products','product_name'))->with('i',(request()->input('page', 1)-1)* 50);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'product_name' => 'required',
            'item_type' => 'required',
            'price' => 'required',
            'diskon_price' => 'required',
        ]);
        $input = $request->all();
        Product::create($input);
        return redirect()->route('product.index')->with('success','Data has been saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $product = Product::find($id);
        return view('product.edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'product_name' => 'required',
            'item_type' => 'required',
            'price' => 'required',
            'diskon_price' => 'required',
        ]);
        $input = $request->all();
        $product = Product::find($id);
        $product->update($input);
        return redirect()->route('product.index')->with('succes','Data has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $product = Product::find($id);
        $product->delete();
        return redirect()->route('product.index')->with('success','Data has been deleted');
    }
}

resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><strong>Create Product</strong></div>

                <div class="card-body">
                  
                    <form action="{{route('product.store')}}" method="post">
                        @csrf
                        <div class="form-group">
                            <strong>Product Name</strong>
                            <input type="text" name="product_name" id="" value="{{old('product_name')}}"
                                class="form-control">
                        </div>
                        <div class="form-group">
                            <strong>Unit</strong>
                            <select name="item_type" id="" class="form-control">
                                <option value="Service">Service</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <strong>Price</strong>
                            <input type="number" name="price" id="" class="form-control" value="{{old('price')}}">
                        </div>
                        <div class="form-group">
                            <strong>Diskon Price</strong>
                            <input type="number" name="diskon_price" id="" class="form-control"
                                value="{{old('diskon_price')}}">
                        </div>

                </div>
                <div class="card-footer">
                    <div class="pull-right">
                        <a href="{{route('product.index')}}" class="btn btn-warning">Back</a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><strong>Edit Product</strong></div>

                <div class="card-body">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops</strong>there is error input
                        @foreach ($errors->all() as $error)
                        <label for="">{{$error}}</label>
                        @endforeach
                    </div>
                    @endif
                    <form action="{{route('product.update',$product->id)}}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <strong>Product Name</strong>
                            <input type="text" name="product_name" id="" value="{{$product->product_name}}"
                                class="form-control">
                        </div>
                        <div class="form-group">
                            <strong>Unit</strong>
                            <select name="item_type" id="" class="form-control">
                                <option value="">Select Unit</option>
                                <option value="Service" {{($product->item_type == "Service") ? 'selected': ''}}>Service</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <strong>Price</strong>
                            <input type="number" name="price" id="" class="form-control" value="{{$product->price}}">
                        </div>
                        <div class="form-group">
                            <strong>Diskon Price</strong>
                            <input type="number" name="diskon_price" id="" class="form-control"
                                value="{{$product->diskon_price}}">
                        </div>

                </div>
                <div class="card-footer">
                    <div class="pull-right">
                        <a href="{{route('product.index')}}" class="btn btn-warning">Back</a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong>List Product</strong>
                </div>
                <div class="card-body">
                    <form action="{{route('product.index')}}" method="get">
                    @csrf
                    <input type="text" name="product_name" id="" placeholder="Product Name" value="{{$product_name}}">
                    <button type="submit" class="btn btn-primary">Search</button>
                    </form>
                    <a href="{{route('product.create')}}" class="btn btn-success pull-right">Add New</a>
                    <br>
                    <br>
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Product Name</th>
                            <th scope="col">Item Type</th>
                            <th scope="col">Price</th>
                            <th scope="col">Disc</th>
                            <th scope="col">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach ($products as $item)
                          <tr>
                              <td>{{++$i}}</td>
                              <td>{{$item->product_name}}</td>
                              <td>{{$item->item_type}}</td>
                             <td>Rp {{number_format($item->price,2,',','.')}}</td>
                              <td>Rp {{number_format($item->diskon_price,2,',','.')}}</td>
                              <td>
                                  <form action="{{route('product.destroy',$item->id)}}" method="post">
                                    <a href="{{route('product.edit',$item->id)}}" class="btn btn-default"><i class="fa fa-edit"></i> Edit</a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-default"><i class="fa fa-trash"></i> Delete</button>
                                  </form>
                              </td>
                            </tr>
                          @endforeach
                        </tbody>
                      </table>
                      {!! $products->links() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection