routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => ['auth']],function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('product','ProductController');
    Route::resource('customer','CustomerController');
    Route::resource('so','SOController');
    Route::get('getCustomer','SOController@getCustomer')->name('getCustomer');
    Route::get('getProduct','SOController@getProduct')->name('getProduct');
});

app/Http/Controllers/SOController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\HeaderSO;
use App\DetailSO;
use App\Product;
use App\Customer;
use Illuminate\Support\Facades\DB;
class SOController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        $startDate = $request->startDate;
        $startDate = empty($startDate) ? date("Y-m-01"): $startDate;
        $endDate = $request->endDate;
        $endDate = empty($endDate) ? date("Y-m-d"): $endDate;
        $salesOrders = DB::table('header_so')
        ->join('customers','header_so.id_customer','=','customers.id')
        ->select('header_so.*','customers.customer_name','customers.contact_person','customers.email')
        ->whereBetween('header_so.posting_date',[$startDate,$endDate])
        ->paginate(50);
        
        return view('so.index',compact('salesOrders','startDate','endDate'))->with('i',(request()->input('page', 1)-1)* 50);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $customers = Customer::all();
        $products = Product::all();
        return view('so.create',compact('customers','products'));
    }
    public function getCustomer(Request $request){
        $id_customer = $request->id_customer;
        $data = Customer::find($id_customer);
        return response()->json($data);
    }
    public function getProduct(Request $request){
        $id_product = $request->id_product;
        $data = Product::find($id_product);
        return response()->json($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $input = $request->all();
        $so_code = collect(DB::select('select so_code from header_so order by so_code desc limit 1'))->first();
        if(empty($so_code->so_code)){
            $nextSoCode ='SO'.'-100000';
        }else{
            $code = $so_code->so_code;
            $expNum = explode('-', $code);
            $nextSoCode = $expNum[0].'-'.(intval($expNum[1]) + 1);
        }
        $input['so_code'] = $nextSoCode;
        HeaderSO::create($input);
        foreach ($request->id_product as $key => $item) {
            # code...
            DetailSO::create([
                'so_code' => $nextSoCode,
                'id_product' => $item,
                'qty' => $request->quantity[$key],
            ]);
        }
        return redirect()->route('so.index')->with('success','Data has been saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $header = DB::table('header_so')->select('*')->where('header_so.so_code',$id)->first();
        $customers = Customer::all();
        $products= Product::all();
        $customer = Customer::where('id', $header->id_customer)->first();
        $product =
        DB::table('detail_so')->select('*')->leftjoin('products','products.id','detail_so.id_product')->where('so_code', $header->so_code)->get();

        return view('so.edit',compact('customers','product','header','customer','products'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $header = HeaderSO::where('so_code',$id)->first();
        $detail = DetailSO::where('so_code',$id);

        $input = $request->all();

        $header->update($input);
        $detail->delete();

        foreach ($request->id_product as $key => $item) {
            # code...
            DetailSO::create([
                'so_code' => $header->so_code,
                'id_product' => $item,
                'qty' => $request->quantity[$key],
            ]);
        }
        return redirect()->route('so.index')->with('success','Data has been saved');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $header = HeaderSO::where('so_code',$id);
        $detail = DetailSO::where('so_code',$id);

        
        $detail->delete();
        $header->delete();

        return redirect()->route('so.index')->with('success','Data has been deleted');
    }
}

resources/views/so/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><strong>Create Sales Order</strong></div>

                <div class="card-body">

                    <form action="{{route('so.store')}}" method="post">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <strong>Customer Name</strong>
                                    <select name="id_customer" id="id_customer" class="form-control">
                                        <option value="">Select Customer</option>
                                        @foreach ($customers as $item)
                                        <option value="{{$item->id}}">{{$item->customer_name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <strong>Contact Person</strong>
                                    <input type="text" name="contact_person" id="contact_person" class="form-control"
                                        readonly>
                                </div>
                                <div class="form-group">
                                    <strong>Email</strong>
                                    <input type="email" name="email" id="email" class="form-control" readonly>
                                </div>
                                <div class="form-group">
                                    <strong>Address</strong>
                                    <textarea name="address" id="address" cols="30" rows="3" class="form-control"
                                        readonly></textarea>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <strong>Subject</strong>
                                    <input type="text" name="subject" id="subject" class="form-control"
                                        value="{{old('subject')}}">
                                </div>
                                <div class="form-group">
                                    <strong>Posting Date</strong>
                                    <input type="date" name="posting_date" id="posting_date" class="form-control"
                                        value="{{old('posting_date')}}">
                                </div>
                                <div class="form-group">
                                    <strong>Delivery Date</strong>
                                    <input type="date" name="delivery_date" id="delivery_date" class="form-control"
                                        value="{{old('delivery_date')}}">
                                </div>
                                <div class="form-group">
                                    <strong>Status</strong>
                                    <input type="text" name="status" id="status" class="form-control" value="Open"
                                        readonly>
                                </div>
                            </div>

                        </div>
                        <div class="pull-right">
                            <button type="button" class="btn btn-success btn-sm add-product" >Add Product</button>
                        </div>
                        <br>
                        <br>
                        <div class="table-responsive">
                        <table class="table table-bordered" id="product-table">
                            <thead>
                                <tr>
                                    <th scope="col" class="col-">Itey Type</th>
                                    <th scope="col" class="col-">Product Name</th>
                                    <th scope="col" class="col-">Price</th>
                                    <th scope="col" class="col-">Qty</th>
                                    <th scope="col" class="col-">Action</th>
                                </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                        <div class="pull-right">
                            <table>
                                <thead>
                                    <tr>
                                        <th>Sub Total</th>
                                        <br>
                                        <th><input type="number" name="sub_total" id="sub_total" class="form-control" readonly>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><strong> Tax (%)</strong></td>
                                        <td><input type="number" name="tax" id="tax" class="form-control"></td>
                                    </tr>
                                    <tr>
                                        <td><strong> Shipment</strong></td>
                                        <td><input type="number" name="shipment" id="shipment" class="form-control">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><strong> Total Payment </strong></td>
                                        <td><input type="number" name="total_payment" id="total_payment" class="form-control" readonly></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                </div>
                <div class="card-footer">
                    <div class="pull-right">
                        <a href="{{route('so.index')}}" class="btn btn-warning">Back</a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="addProduct" tabindex="-1" role="dialog" aria-labelledby="addProduct" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Product</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <strong>Product Name</strong>
                    <select name="id_product" id="id_product" class="form-control" style="width: 100%;">
                        <option value="">Select Product</option>
                        @foreach ($products as $item)
                        <option value="{{$item->id}}">{{$item->product_name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <strong>Item Type</strong>
                    <input type="text" name="item_type" id="item_type" class="form-control" readonly>
                </div>
                <div class="form-group">
                    <strong>Price</strong>
                    <input type="number" name="price" id="price" class="form-control" readonly>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="addProduct()">Save changes</button>
            </div>
        </div>
    </div>
</div>
@endsection
@push('script')
<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
    });
    $("#id_customer").select2({
        placeholder: 'Select Customer',
        language: 'id',
        allowClear: true
    });
    $("#id_product").select2({
        placeholder: 'Select Product',
        language: 'id',
        allowClear: true,
        dropdownParent: $("#addProduct")
    });
    $('.add-product').click(function(){
        var id_customer = document.getElementById("id_customer");
        var posting_date = document.getElementById("posting_date");
        var delivery_date = document.getElementById("delivery_date");
        if (id_customer.value != "" && posting_date.value != "" && delivery_date.value != "") {
            $('#addProduct').modal({
			    backdrop: 'static'
		    });
        }else{
            alert('Please complete input field');
        }
    });
    function addProduct(){
        id_product = document.getElementById("id_product").selectedIndex;
        product_name = $("#id_product option:selected" ).text();
        var item_type = document.getElementById("item_type");
        var price = document.getElementById("price");
        $("#product-table > tbody").append("<tr><td class='col-'><input type='hidden' name='id_product[]' value="+id_product+" readonly/><input type='text' name='product_name[]' value='"+product_name+"' readonly/></td><td class='col-'><input type='text' name='item_type[]' value='"+item_type.value+"' readonly></td><td class='col-'><input type='number' class='price' name='price[]' value='"+price.value+"' readonly/></td><td class='col-'><input type='number' class='quantity' id='quantity' name='quantity[]'></td><td class='col-'><button class='btn btn-sm btn-danger btn-delete'>Delete</button></td></tr>");
        document.getElementById("item_type").value ="";
        document.getElementById("price").value ="";
        $('#addProduct').modal('toggle');
    }
    function subTotal(){
        var sum = 0.0;
        $('#product-table > tbody  > tr').each(function() {
            var qty = $(this).find('.quantity').val();
            var price = $(this).find('.price').val();
            var amount = parseFloat(qty) * parseFloat(price);
            amount = isNaN(amount) ? 0 : amount;  //checks for initial empty text boxes
            sum += amount;
        });
        $("#sub_total").val(sum);
    }
    function grandTotal(){
        var tax = $("#tax").val();
        var subTotal = $("#sub_total").val();
        var shipment = $("#shipment").val();
        tax = isNaN(parseFloat(tax)) ? 0 : tax;
        shipment = isNaN(parseFloat(shipment)) ? 0 : shipment;
        var calTax = (tax / 100) * subTotal;
        var total_payment = parseFloat(subTotal) + parseFloat(calTax) + parseFloat(shipment);
        $("#total_payment").val(total_payment);
    }
    $(document).on('change','#quantity',function(){
     subTotal();
    });
    
    $("#id_customer").change(function(){
        const id_customer = $(this).val();
        $.ajax({
                url: "{{route('getCustomer')}}",
                type: "get",
                dataType: "json",
                async: true,
                data: {
                    id_customer: id_customer
                },
                success: function(data){
                    if(data.id === undefined){
                        $('#contact_person').val('');
                        $('#email').val('');
                        $('#address').val('');
                    }else{
                        $('#contact_person').val(data.contact_person);
                        $('#email').val(data.email);
                        $('#address').val(data.address);
                    }
                }     
            });  
    });
    $("#id_product").change(function(){
        const id_product = $(this).val();
        $.ajax({
                url: "{{route('getProduct')}}",
                type: "get",
                dataType: "json",
                async: true,
                data: {
                    id_product: id_product
                },
                success: function(data){
                    if(data.id === undefined){
                        $('#item_type').val('');
                        $('#price').val('');
                    }else{
                        $('#item_type').val(data.item_type);
                        $('#price').val(data.price);
                    }
                }     
            });  
    });
    $("#tax").change(function(){
        grandTotal();
    })
    $("#shipment").change(function(){
        grandTotal();
    })
    $("body").on("click", ".btn-delete", function(){
        $(this).parents("tr").remove();
        subTotal();
    });
</script>
@endpush

resources/views/so/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong>List Sales Order</strong>
                </div>
                <div class="card-body">
                    <form action="{{route('so.index')}}" method="get">
                    @csrf
                    <input type="date" name="startDate" id="" value="{{ date('Y-m-d', strtotime($startDate))}}" >
                    <input type="date" name="endDate" id="" value="{{ date('Y-m-d', strtotime($endDate))}}" >
                    <button type="submit" class="btn btn-primary">Search</button>
                    </form>
                    <a href="{{route('so.create')}}" class="btn btn-success pull-right">Add New</a>
                    <br>
                    <br>
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">SO Code</th>
                            <th scope="col">Customer Name</th>
                            <th scope="col">Contact Person</th>
                            <th scope="col">Email</th>
                            <th scope="col">Posting Date</th>
                            <th scope="col">Delivery Date</th>
                            <th scope="col">Status</th>
                            <th scope="col">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach ($salesOrders as $item)
                          <tr>
                              <td>{{++$i}}</td>
                              <td>{{$item->so_code}}</td>
                              <td>{{$item->customer_name}}</td>
                              <td>{{$item->contact_person}}</td>
                              <td>{{$item->email}}</td>
                              <td>{{$item->posting_date}}</td>
                              <td>{{$item->delivery_date}}</td>
                              <td>{{$item->status}}</td>                        
                              <td>
                                  <form action="{{route('so.destroy',$item->so_code)}}" method="post">
                                    <a href="{{route('so.edit',$item->so_code)}}" class="btn btn-default"><i class="fa fa-edit"></i> Edit</a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-default"><i class="fa fa-trash"></i> Delete</button>
                                  </form>
                              </td>
                            </tr>
                          @endforeach
                        </tbody>
                      </table>
                      {!! $salesOrders->links() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection