routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => ['auth']],function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('product','ProductController');
    Route::resource('customer','CustomerController');
    Route::resource('so','SOController');
    Route::get('getCustomer','SOController@getCustomer')->name('getCustomer');
    Route::get('getProduct','SOController@getProduct')->name('getProduct');
});

app/Customer.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model {
    //
    protected $fillable=[ 
    'customer_name',
    'address',
    'zip',
    'city',
    'province',
    'contact_person',
    'phone',
    'email',
    'country'
    ];
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Customer;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        $customer_name = $request->customer_name;
        $customers = Customer::where('customer_name','LIKE','%'.$customer_name.'%')
        ->paginate(50);
        return view('customer.index',compact('customers','customer_name'))->with('i',(request()->input('page', 1)-1)* 50);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('customer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'customer_name' => 'required',
            'address' => 'required',
            'zip' => 'required',
            'city' => 'required',
            'province' => 'required',
            'contact_person' => 'required',
            'country'=> 'required'
           
        ]);
        $input = $request->all();
        Customer::create($input);
        return redirect()->route('customer.index')->with('success','Data has been saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $customer = Customer::find($id);
        return view('customer.edit',compact('customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'customer_name' => 'required',
            'address' => 'required',
            'zip' => 'required',
            'city' => 'required',
            'province' => 'required',
            'contact_person' => 'required',
            'country'=> 'required'
        ]);
        $input = $request->all();
        $customer = Customer::find($id);
        $customer->update($input);
        return redirect()->route('customer.index')->with('success','Data has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $customer = Customer::find($id);
        $customer->delete();
        return redirect()->route('customer.index')->with('success','Data has been deleted');
    }
}

resources/views/customer/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><strong>Create Customer</strong></div>

                <div class="card-body">
                  
                    <form action="{{route('customer.store')}}" method="post">
                        @csrf
                        <div class="form-group">
                            <strong>Customer Name</strong>
                            <input type="text" name="customer_name" id="" value="{{old('customer_name')}}"
                                class="form-control">
                        </div>
                        <div class="form-group">
                            <strong>City</strong>
                            <input type="text" name="city" id="" class="form-control" value="{{old('city')}}">
                        </div>
                        <div class="form-group">
                            <strong>Province</strong>
                            <input type="text" name="province" id="" class="form-control" value="{{old('province')}}">
                        </div>
                        <div class="form-group">
                            <strong>Contry</strong>
                            <input type="text" name="country" id="" class="form-control" value="{{old('country')}}">
                        </div>
                                                
                        <div class="form-group">
                            <strong>Zip Code</strong>
                            <input type="number" name="zip" id="" class="form-control" value="{{old('zip')}}">
                        </div>
                        <div class="form-group">
                            <strong>Address</strong>
                            <textarea name="address" id="" cols="30" rows="10" class="form-control">{{old('address')}}</textarea>
                        </div>
                        <div class="form-group">
                            <strong>Contact Person</strong>
                            <input type="text" name="contact_person" id="" class="form-control" value="{{old('contact_person')}}">
                        </div>
                        <div class="form-group">
                            <strong>Email</strong>
                            <input type="email" name="email" id="" class="form-control" value="{{old('email')}}">
                        </div>
                        <div class="form-group">
                            <strong>Phone</strong>
                            <input type="text" name="phone" id="" class="form-control" value="{{old('phone')}}">
                        </div>
                </div>
                <div class="card-footer">
                    <div class="pull-right">
                        <a href="{{route('customer.index')}}" class="btn btn-warning">Back</a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/customer/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><strong>Edit Customer</strong></div>

                <div class="card-body">
                  
                    <form action="{{route('customer.update',$customer->id)}}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <strong>Customer Name</strong>
                            <input type="text" name="customer_name" id="" value="{{$customer->customer_name}}"
                                class="form-control">
                        </div>
                        <div class="form-group">
                            <strong>City</strong>
                            <input type="text" name="city" id="" class="form-control" value="{{$customer->city}}">
                        </div>
                        <div class="form-group">
                            <strong>Province</strong>
                            <input type="text" name="province" id="" class="form-control" value="{{$customer->province}}">
                        </div>
                        <div class="form-group">
                            <strong>Country</strong>
                            <input type="text" name="country" id="" class="form-control" value="{{$customer->country}}">
                        </div>
                        
                        <div class="form-group">
                            <strong>Zip Code</strong>
                            <input type="number" name="zip" id="" class="form-control" value="{{$customer->zip}}">
                        </div>
                        <div class="form-group">
                            <strong>Address</strong>
                            <textarea name="address" id="" cols="30" rows="10" class="form-control">{{$customer->address}}</textarea>
                        </div>
                        <div class="form-group">
                            <strong>Contact Person</strong>
                            <input type="text" name="contact_person" id="" class="form-control" value="{{$customer->contact_person}}">
                        </div>
                        <div class="form-group">
                            <strong>Email</strong>
                            <input type="email" name="email" id="" class="form-control" value="{{$customer->email}}">
                        </div>
                        <div class="form-group">
                            <strong>Phone</strong>
                            <input type="text" name="phone" id="" class="form-control" value="{{$customer->phone}}">
                        </div>

                </div>
                <div class="card-footer">
                    <div class="pull-right">
                        <a href="{{route('customer.index')}}" class="btn btn-warning">Back</a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/customer/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong>List Customer</strong>
                </div>
                <div class="card-body">
                    <form action="{{route('customer.index')}}" method="get">
                    @csrf
                    <input type="text" name="customer_name" id="" placeholder="Customer Name" value="{{$customer_name}}">
                    <button type="submit" class="btn btn-primary">Search</button>
                    </form>
                    <a href="{{route('customer.create')}}" class="btn btn-success pull-right">Add New</a>
                    <br>
                    <br>
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Customer Name</th>
                            <th scope="col">Zip</th>
                            <th scope="col">City</th>
                            <th scope="col">Province</th>
                            <th scope="col">Email</th>
                            <th scope="col">Contact Person</th>
                            <th scope="col">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach ($customers as $item)
                          <tr>
                              <td>{{++$i}}</td>
                              <td>{{$item->customer_name}}</td>
                              <td>{{$item->zip}}</td>
                              <td>{{$item->city}}</td>
                              <td>{{$item->province}}</td>
                              <td>{{$item->email}}</td>
                              <td>{{$item->contact_person}}</td>
                              <td>
                                  <form action="{{route('customer.destroy',$item->id)}}" method="post">
                                    <a href="{{route('customer.edit',$item->id)}}" class="btn btn-default"><i class="fa fa-edit"></i> Edit</a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-default"><i class="fa fa-trash"></i> Delete</button>
                                  </form>
                              </td>
                            </tr>
                          @endforeach
                        </tbody>
                      </table>
                      {!! $customers->links() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection